functionsDirectory = "/home/mamadou/Documents/CODES/opensya/code-2/elsy/elsy-phase5-real-test/elsy/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/mamadou/Documents/CODES/opensya/code-2/elsy/elsy-phase5-real-test/elsy"
publishOrigin = "default"
commandOrigin = "config"
command = "corepack enable && pnpm install --no-frozen-lockfile && pnpm -r run build && pnpm run generate:netlify"
functions = "/home/mamadou/Documents/CODES/opensya/code-2/elsy/elsy-phase5-real-test/elsy/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]